version: '3.9'

services:
  leaflet-app:
      container_name: leaflet-app
      build:
        context: .
        dockerfile: Dockerfile
      image: leaflet-app:latest
      restart: unless-stopped
      ports:
        - 4210:80
      networks:
        - npm-network

networks:
    npm-network:
      name: npm-stack_default
      external: true
